### ISSUE TITLE
tool for slides

### ISSUE THREAD

**Issue by allanj** [deep-spin/tutorial#1]
Can I ask what software you use to create the slides? It looks great

**Comment by vene** [comment]
Hi, thanks for the kind words! It is beamer, we shared the sources here: https://github.com/deep-spin/tutorial-latent-struct-src/

**Comment by allanj** [comment]
The page you shared is 404.

**Comment by vene** [comment]
sorry my bad i had left the repo private, try again

**Comment by allanj** [comment]
Thanks!
